### ISSUE TITLE
Failed to parse metadata from "super.img"

### ISSUE THREAD

**Issue by ildar** [tchebb/parse-dynparts#1]
dunno why but I didn't see it working with any of the images I have.
Example: https://doogeemall.com/community/xenforum/topic/61279/doogee-s59pro-new-eea-software-version-released-doogee-s59pro-android10-20220214
With this image it just:
> $  parse-android-dynparts super.img 
> [E][liblp]Logical partition metadata has invalid geometry magic signature.
> [E][liblp]Logical partition metadata has invalid geometry magic signature.
> Failed to parse metadata from "super.img"

Though I successfully flashed it and it works:
> $  fastboot flash super super.img 

I may misunderstand something, please guide me.

**Comment by tchebb** [comment]
Looks like the `super.img` in that update package is a sparse image file:
```
$ file super.img
super.img: Android sparse image, version: 1.0, Total of 1048576 4096-byte output blocks in 3108 input chunks.
```
[Sparse image](https://web.archive.org/web/20220322054458/https://source.android.com/devices/bootloader/images#sparse-image-format) is another Android-specific format for specifying only the parts of a disk image that contain meaningful data. It's often stacked on top of raw ext4 images as well as dynamic partition images like you have.

In order to use parse-android-dynparts on your image, you'll first have to "unsparse" it. You can use the simg2img tool from upstream Android for that. Although simg2img is an [official Android tool](https://android.googlesource.com/platform/system/core/+/ab2d6cdc8fcab494f06effc7a9eb1855313bcf3b/libsparse/simg2img.cpp), you'll probably want to use one of the unofficial distributions of it, since building it as part of Android requires downloading the entire AOSP tree. [nmeum/android-tools](https://github.com/nmeum/android-tools) is a self-contained distribution of lots of tools from AOSP, including simg2img, and might already be packaged for your Linux distro as `android-tools`. Or [anestisb/android-simg2img](https://github.com/anestisb/android-simg2img) is a self-contained distribusion of just simg2img.

There is a note in the README about this, FWIW, but it's easy to miss because Google uses the filename `super.img` for both sparse and raw images with no indication of which is which:
> Depending on the source of the image you're working with, this may initially be a sparse image, which you'll have to unsparse using the standard Android `simg2img` tool …

**Comment by ildar** [comment]
thanks for the explanation.
The image we discuss was successfully flashed with fastboot so I assume
that exactly the same raw data would be read from the `super` partition
(mmc0pxx). Am I right?

I hoped that this tool would help reading the raw `super` partition
containing Android dynparts.

I still can't figure out where's my mistake/misunderstanding.

**Comment by tchebb** [comment]
> I assume that exactly the same raw data would be read from the `super` partition (mmc0pxx). Am I right?

No, that's not correct when the image you flash is sparse. fastboot knows about sparse images and will extract the contents when you tell it to flash one. So the `super` partition is close to the image you get from running simg2img on `super.img`. (I say "close" and not "identical" because simg2img fills unspecified areas with zeroes, while fastboot leaves them unmodified on the device.)

parse-android-dynparts works fine for me on the unsparsed version of the example image you linked to, FYI.

**Comment by ildar** [comment]
yes, it's clear now. Thanks for teaching.

**Comment by ildar** [comment]
I guess that my mistake is: sparse format is not a raw format.
