### ISSUE TITLE
Failed to parse metadata

### ISSUE THREAD

**Issue by jeffeste** [tchebb/parse-dynparts#2]
```
$ sudo losetup -r /dev/loop19 ../../ssuper.img
$ dmsetup create --concise "$(parse-android-dynparts /dev/loop19)"
[E][liblp]std::unique_ptr<android::fs_mgr::LpMetadata> android::fs_mgr::ReadMetadata(const std::string&, uint32_t) open failed: /dev/loop19
Failed to parse metadata from "/dev/loop19"
```

I built with make

**Comment by jeffeste** [comment]
Perhaps it's an issue with the image itself. Individual images unpacked with lpunpack fail to mount. 
If you want to investigate yourself this is the firmware that I used: citrus_eea_global_images_V14.0.2.0.SJFEUXM_20230509.0000.00_12.0_eea

**Comment by jeffeste** [comment]
I feel the issue is that the image does not specify the ext4 magic headers, at least that is the problem with the individual slots unpacked with lpunpack.
Dmesg shows: `EXT4-fs (loop10): couldn't mount RDWR because of unsupported optional features (4000)`
Thus setting the system image like this:
```
$ losetup -P -f --show system.img
$ sudo mount -t ext4 -o ro,noload /dev/loop10 system/
```
manages to mount it.

**Comment by tchebb** [comment]
The "Failed to parse metadata" error is a result of the error on the previous line:
```
[E][liblp]std::unique_ptrandroid::fs_mgr::LpMetadata android::fs_mgr::ReadMetadata(const std::string&, uint32_t) open failed: /dev/loop19
```

Note the "open failed". I suspect the open fails because you're not running parse-android-dynparts as root. The instructions in the README assume a root shell. When running from a non-root shell, you need to invoke both `dmsetup create` and `parse-android-dynparts` via sudo, like this:
```
$ sudo dmsetup create --concise "$(sudo parse-android-dynparts /dev/loop19)"
```

**Comment by tchebb** [comment]
The "couldn't mount RDWR" error in dmesg is entirely separate. That's expected for most new Android images, because Android ext4 images use the ext4 "shared blocks" mode (more details [here](https://threadreaderapp.com/thread/1170404631865778177.html)), which saves space but makes the filesystem read-only. As you noticed, passing `-o ro` lets you mount it.

**Comment by jeffeste** [comment]
> The "Failed to parse metadata" error is a result of the error on the previous line:
> 
> ```
> [E][liblp]std::unique_ptrandroid::fs_mgr::LpMetadata android::fs_mgr::ReadMetadata(const std::string&, uint32_t) open failed: /dev/loop19
> ```
> 
> Note the "open failed". I suspect the open fails because you're not running parse-android-dynparts as root. The instructions in the README assume a root shell. When running from a non-root shell, you need to invoke both `dmsetup create` and `parse-android-dynparts` via sudo, like this:
> 
> ```
> $ sudo dmsetup create --concise "$(sudo parse-android-dynparts /dev/loop19)"
> ```

Running with sudo yields the same error but executing from a root shell worked

**Comment by tchebb** [comment]
Did you add `sudo` in both places on the line (at the beginning and also inside the `$()`)? That ought to work.

**Comment by jeffeste** [comment]
> Did you add `sudo` in both places on the line (at the beginning and also inside the `$()`)? That ought to work.

Doing that causes it to not read parse-android-dynparts from my PATH
```
$ sudo dmsetup create --concise "$(sudo parse-android-dynparts /dev/loop19)"
sudo: parse-android-dynparts: command not found
```

Manually referencing it causes it to not execute
```
$ sudo dmsetup create --concise "$(sudo ./media/.../build/parse-android-dynparts /dev/loop19)"
sudo: .../build/parse-android-dynparts: command not found
```

```
$ sudo dmsetup create --concise "$(sudo bash .../build/parse-android-dynparts /dev/loop19)"
.../build/parse-android-dynparts: .../build/parse-android-dynparts: cannot execute binary file
```

**Comment by tchebb** [comment]
Hm, not sure why the middle one would fail. The last one won't work because `parse-android-dynparts` is a binary and not a Bash script. You might have meant to pass the whole command to `bash -c`, but no explicit Bash invocation should be needed at all.

Regardless, since you solved it using a root shell, I'm going to close this issue. Hope you were able to do what you wanted to!
